package jinsoftms.database.khdata;

import java.math.BigDecimal;
import java.util.Date;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Name
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Na
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String na;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Link
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Short link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String icode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.IC
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String ic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.BIC
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String bic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Type
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Kind
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Form
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.DIR
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String dir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Storey
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Short storey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.MFE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal mfe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.State
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.JAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal jaream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.JAreaF
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal jareaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.UAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal uaream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.UAreaF
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal uareaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ZLevel
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String zlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SB
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String sb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Memo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YZPerson
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String yzperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ZHPerson
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String zhperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YZID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Integer yzid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ZHID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Integer zhid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YZDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date yzdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ZHDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date zhdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Money
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.PayType
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SMoneyM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal smoneym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SMoneyD
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal smoneyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.MMoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal mmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.PDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String pdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YZICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String yzicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.ZHICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String zhicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Aoo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String aoo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Boo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String boo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Coo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String coo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SBDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sbdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SEDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.zhdate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date zhdate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.zxday
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Short zxday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.yj
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal yj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarMoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal carmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.DZL
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal dzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YTZ
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String ytz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.DZBDATE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date dzbdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.DZEDATE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date dzedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.BBS
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Short bbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Doo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String doo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Eoo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String eoo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Note
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YsCFlag
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String yscflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.NoDebitQ
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String nodebitq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.NoCk
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String nock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Gprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal gprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Mtype
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String mtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SKeyDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date skeydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.BalanceReason
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String balancereason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SKeyReason
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String skeyreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.GJAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal gjaream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.GGprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal ggprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Zjprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal zjprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Zjmoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal zjmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.YTG
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String ytg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SUnitDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sunitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CommonModulus
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal commonmodulus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.AcCode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String accode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.RmNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String rmno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Cartype
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String carno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarRendateb
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date carrendateb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarRendatee
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date carrendatee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarICNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String caricno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.DebitNoteAddr
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String debitnoteaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.BankAccntNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String bankaccntno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CSdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date csdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.idate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date idate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SBDate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sbdate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SEDate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sedate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SBDate2
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sbdate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.SEDate2
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date sedate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarState
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String carstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarZdateb
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date carzdateb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.CarZdatee
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date carzdatee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.PJaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal pjaream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.PUaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal puaream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.PGJaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private BigDecimal pgjaream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Prdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date prdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.PrNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String prno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Psdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date psdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Scdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date scdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.Audate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private Date audate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Room.DailyEvent
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    private String dailyevent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ID
     *
     * @return the value of Room.ID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ID
     *
     * @param id the value for Room.ID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Name
     *
     * @return the value of Room.Name
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Name
     *
     * @param name the value for Room.Name
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Na
     *
     * @return the value of Room.Na
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getNa() {
        return na;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Na
     *
     * @param na the value for Room.Na
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setNa(String na) {
        this.na = na == null ? null : na.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Link
     *
     * @return the value of Room.Link
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Short getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Link
     *
     * @param link the value for Room.Link
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setLink(Short link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ICode
     *
     * @return the value of Room.ICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getIcode() {
        return icode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ICode
     *
     * @param icode the value for Room.ICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setIcode(String icode) {
        this.icode = icode == null ? null : icode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.IC
     *
     * @return the value of Room.IC
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getIc() {
        return ic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.IC
     *
     * @param ic the value for Room.IC
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setIc(String ic) {
        this.ic = ic == null ? null : ic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.BIC
     *
     * @return the value of Room.BIC
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getBic() {
        return bic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.BIC
     *
     * @param bic the value for Room.BIC
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setBic(String bic) {
        this.bic = bic == null ? null : bic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Type
     *
     * @return the value of Room.Type
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Type
     *
     * @param type the value for Room.Type
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Kind
     *
     * @return the value of Room.Kind
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Kind
     *
     * @param kind the value for Room.Kind
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Form
     *
     * @return the value of Room.Form
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Form
     *
     * @param form the value for Room.Form
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.DIR
     *
     * @return the value of Room.DIR
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getDir() {
        return dir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.DIR
     *
     * @param dir the value for Room.DIR
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDir(String dir) {
        this.dir = dir == null ? null : dir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Storey
     *
     * @return the value of Room.Storey
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Short getStorey() {
        return storey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Storey
     *
     * @param storey the value for Room.Storey
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setStorey(Short storey) {
        this.storey = storey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.MFE
     *
     * @return the value of Room.MFE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getMfe() {
        return mfe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.MFE
     *
     * @param mfe the value for Room.MFE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setMfe(BigDecimal mfe) {
        this.mfe = mfe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.State
     *
     * @return the value of Room.State
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.State
     *
     * @param state the value for Room.State
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.JAreaM
     *
     * @return the value of Room.JAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getJaream() {
        return jaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.JAreaM
     *
     * @param jaream the value for Room.JAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setJaream(BigDecimal jaream) {
        this.jaream = jaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.JAreaF
     *
     * @return the value of Room.JAreaF
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getJareaf() {
        return jareaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.JAreaF
     *
     * @param jareaf the value for Room.JAreaF
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setJareaf(BigDecimal jareaf) {
        this.jareaf = jareaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.UAreaM
     *
     * @return the value of Room.UAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getUaream() {
        return uaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.UAreaM
     *
     * @param uaream the value for Room.UAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setUaream(BigDecimal uaream) {
        this.uaream = uaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.UAreaF
     *
     * @return the value of Room.UAreaF
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getUareaf() {
        return uareaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.UAreaF
     *
     * @param uareaf the value for Room.UAreaF
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setUareaf(BigDecimal uareaf) {
        this.uareaf = uareaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ZLevel
     *
     * @return the value of Room.ZLevel
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getZlevel() {
        return zlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ZLevel
     *
     * @param zlevel the value for Room.ZLevel
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZlevel(String zlevel) {
        this.zlevel = zlevel == null ? null : zlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SB
     *
     * @return the value of Room.SB
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getSb() {
        return sb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SB
     *
     * @param sb the value for Room.SB
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSb(String sb) {
        this.sb = sb == null ? null : sb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Memo
     *
     * @return the value of Room.Memo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Memo
     *
     * @param memo the value for Room.Memo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YZPerson
     *
     * @return the value of Room.YZPerson
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getYzperson() {
        return yzperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YZPerson
     *
     * @param yzperson the value for Room.YZPerson
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYzperson(String yzperson) {
        this.yzperson = yzperson == null ? null : yzperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ZHPerson
     *
     * @return the value of Room.ZHPerson
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getZhperson() {
        return zhperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ZHPerson
     *
     * @param zhperson the value for Room.ZHPerson
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZhperson(String zhperson) {
        this.zhperson = zhperson == null ? null : zhperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YZID
     *
     * @return the value of Room.YZID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Integer getYzid() {
        return yzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YZID
     *
     * @param yzid the value for Room.YZID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYzid(Integer yzid) {
        this.yzid = yzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ZHID
     *
     * @return the value of Room.ZHID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Integer getZhid() {
        return zhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ZHID
     *
     * @param zhid the value for Room.ZHID
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZhid(Integer zhid) {
        this.zhid = zhid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SDate
     *
     * @return the value of Room.SDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SDate
     *
     * @param sdate the value for Room.SDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YZDate
     *
     * @return the value of Room.YZDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getYzdate() {
        return yzdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YZDate
     *
     * @param yzdate the value for Room.YZDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYzdate(Date yzdate) {
        this.yzdate = yzdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ZHDate
     *
     * @return the value of Room.ZHDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getZhdate() {
        return zhdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ZHDate
     *
     * @param zhdate the value for Room.ZHDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZhdate(Date zhdate) {
        this.zhdate = zhdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Money
     *
     * @return the value of Room.Money
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Money
     *
     * @param money the value for Room.Money
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.PayType
     *
     * @return the value of Room.PayType
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.PayType
     *
     * @param paytype the value for Room.PayType
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SMoneyM
     *
     * @return the value of Room.SMoneyM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getSmoneym() {
        return smoneym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SMoneyM
     *
     * @param smoneym the value for Room.SMoneyM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSmoneym(BigDecimal smoneym) {
        this.smoneym = smoneym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SMoneyD
     *
     * @return the value of Room.SMoneyD
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getSmoneyd() {
        return smoneyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SMoneyD
     *
     * @param smoneyd the value for Room.SMoneyD
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSmoneyd(BigDecimal smoneyd) {
        this.smoneyd = smoneyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.MMoney
     *
     * @return the value of Room.MMoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getMmoney() {
        return mmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.MMoney
     *
     * @param mmoney the value for Room.MMoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setMmoney(BigDecimal mmoney) {
        this.mmoney = mmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.PDate
     *
     * @return the value of Room.PDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.PDate
     *
     * @param pdate the value for Room.PDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPdate(String pdate) {
        this.pdate = pdate == null ? null : pdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YZICode
     *
     * @return the value of Room.YZICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getYzicode() {
        return yzicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YZICode
     *
     * @param yzicode the value for Room.YZICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYzicode(String yzicode) {
        this.yzicode = yzicode == null ? null : yzicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.ZHICode
     *
     * @return the value of Room.ZHICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getZhicode() {
        return zhicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.ZHICode
     *
     * @param zhicode the value for Room.ZHICode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZhicode(String zhicode) {
        this.zhicode = zhicode == null ? null : zhicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Aoo
     *
     * @return the value of Room.Aoo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getAoo() {
        return aoo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Aoo
     *
     * @param aoo the value for Room.Aoo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setAoo(String aoo) {
        this.aoo = aoo == null ? null : aoo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Boo
     *
     * @return the value of Room.Boo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getBoo() {
        return boo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Boo
     *
     * @param boo the value for Room.Boo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setBoo(String boo) {
        this.boo = boo == null ? null : boo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Coo
     *
     * @return the value of Room.Coo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getCoo() {
        return coo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Coo
     *
     * @param coo the value for Room.Coo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCoo(String coo) {
        this.coo = coo == null ? null : coo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SBDate
     *
     * @return the value of Room.SBDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSbdate() {
        return sbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SBDate
     *
     * @param sbdate the value for Room.SBDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSbdate(Date sbdate) {
        this.sbdate = sbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SEDate
     *
     * @return the value of Room.SEDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSedate() {
        return sedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SEDate
     *
     * @param sedate the value for Room.SEDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSedate(Date sedate) {
        this.sedate = sedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.zhdate1
     *
     * @return the value of Room.zhdate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getZhdate1() {
        return zhdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.zhdate1
     *
     * @param zhdate1 the value for Room.zhdate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZhdate1(Date zhdate1) {
        this.zhdate1 = zhdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.zxday
     *
     * @return the value of Room.zxday
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Short getZxday() {
        return zxday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.zxday
     *
     * @param zxday the value for Room.zxday
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZxday(Short zxday) {
        this.zxday = zxday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.yj
     *
     * @return the value of Room.yj
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getYj() {
        return yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.yj
     *
     * @param yj the value for Room.yj
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYj(BigDecimal yj) {
        this.yj = yj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarMoney
     *
     * @return the value of Room.CarMoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getCarmoney() {
        return carmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarMoney
     *
     * @param carmoney the value for Room.CarMoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarmoney(BigDecimal carmoney) {
        this.carmoney = carmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.DZL
     *
     * @return the value of Room.DZL
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getDzl() {
        return dzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.DZL
     *
     * @param dzl the value for Room.DZL
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDzl(BigDecimal dzl) {
        this.dzl = dzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YTZ
     *
     * @return the value of Room.YTZ
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getYtz() {
        return ytz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YTZ
     *
     * @param ytz the value for Room.YTZ
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYtz(String ytz) {
        this.ytz = ytz == null ? null : ytz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.DZBDATE
     *
     * @return the value of Room.DZBDATE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getDzbdate() {
        return dzbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.DZBDATE
     *
     * @param dzbdate the value for Room.DZBDATE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDzbdate(Date dzbdate) {
        this.dzbdate = dzbdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.DZEDATE
     *
     * @return the value of Room.DZEDATE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getDzedate() {
        return dzedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.DZEDATE
     *
     * @param dzedate the value for Room.DZEDATE
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDzedate(Date dzedate) {
        this.dzedate = dzedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.BBS
     *
     * @return the value of Room.BBS
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Short getBbs() {
        return bbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.BBS
     *
     * @param bbs the value for Room.BBS
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setBbs(Short bbs) {
        this.bbs = bbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Doo
     *
     * @return the value of Room.Doo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getDoo() {
        return doo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Doo
     *
     * @param doo the value for Room.Doo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDoo(String doo) {
        this.doo = doo == null ? null : doo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Eoo
     *
     * @return the value of Room.Eoo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getEoo() {
        return eoo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Eoo
     *
     * @param eoo the value for Room.Eoo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setEoo(String eoo) {
        this.eoo = eoo == null ? null : eoo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Note
     *
     * @return the value of Room.Note
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Note
     *
     * @param note the value for Room.Note
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YsCFlag
     *
     * @return the value of Room.YsCFlag
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getYscflag() {
        return yscflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YsCFlag
     *
     * @param yscflag the value for Room.YsCFlag
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYscflag(String yscflag) {
        this.yscflag = yscflag == null ? null : yscflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.NoDebitQ
     *
     * @return the value of Room.NoDebitQ
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getNodebitq() {
        return nodebitq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.NoDebitQ
     *
     * @param nodebitq the value for Room.NoDebitQ
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setNodebitq(String nodebitq) {
        this.nodebitq = nodebitq == null ? null : nodebitq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.NoCk
     *
     * @return the value of Room.NoCk
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getNock() {
        return nock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.NoCk
     *
     * @param nock the value for Room.NoCk
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setNock(String nock) {
        this.nock = nock == null ? null : nock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Gprice
     *
     * @return the value of Room.Gprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getGprice() {
        return gprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Gprice
     *
     * @param gprice the value for Room.Gprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setGprice(BigDecimal gprice) {
        this.gprice = gprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Mtype
     *
     * @return the value of Room.Mtype
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getMtype() {
        return mtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Mtype
     *
     * @param mtype the value for Room.Mtype
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setMtype(String mtype) {
        this.mtype = mtype == null ? null : mtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SKeyDate
     *
     * @return the value of Room.SKeyDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSkeydate() {
        return skeydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SKeyDate
     *
     * @param skeydate the value for Room.SKeyDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSkeydate(Date skeydate) {
        this.skeydate = skeydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.BalanceReason
     *
     * @return the value of Room.BalanceReason
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getBalancereason() {
        return balancereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.BalanceReason
     *
     * @param balancereason the value for Room.BalanceReason
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setBalancereason(String balancereason) {
        this.balancereason = balancereason == null ? null : balancereason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SKeyReason
     *
     * @return the value of Room.SKeyReason
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getSkeyreason() {
        return skeyreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SKeyReason
     *
     * @param skeyreason the value for Room.SKeyReason
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSkeyreason(String skeyreason) {
        this.skeyreason = skeyreason == null ? null : skeyreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.GJAreaM
     *
     * @return the value of Room.GJAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getGjaream() {
        return gjaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.GJAreaM
     *
     * @param gjaream the value for Room.GJAreaM
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setGjaream(BigDecimal gjaream) {
        this.gjaream = gjaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.GGprice
     *
     * @return the value of Room.GGprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getGgprice() {
        return ggprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.GGprice
     *
     * @param ggprice the value for Room.GGprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setGgprice(BigDecimal ggprice) {
        this.ggprice = ggprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Zjprice
     *
     * @return the value of Room.Zjprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getZjprice() {
        return zjprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Zjprice
     *
     * @param zjprice the value for Room.Zjprice
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZjprice(BigDecimal zjprice) {
        this.zjprice = zjprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Zjmoney
     *
     * @return the value of Room.Zjmoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getZjmoney() {
        return zjmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Zjmoney
     *
     * @param zjmoney the value for Room.Zjmoney
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setZjmoney(BigDecimal zjmoney) {
        this.zjmoney = zjmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.YTG
     *
     * @return the value of Room.YTG
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getYtg() {
        return ytg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.YTG
     *
     * @param ytg the value for Room.YTG
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setYtg(String ytg) {
        this.ytg = ytg == null ? null : ytg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SUnitDate
     *
     * @return the value of Room.SUnitDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSunitdate() {
        return sunitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SUnitDate
     *
     * @param sunitdate the value for Room.SUnitDate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSunitdate(Date sunitdate) {
        this.sunitdate = sunitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CommonModulus
     *
     * @return the value of Room.CommonModulus
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getCommonmodulus() {
        return commonmodulus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CommonModulus
     *
     * @param commonmodulus the value for Room.CommonModulus
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCommonmodulus(BigDecimal commonmodulus) {
        this.commonmodulus = commonmodulus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.AcCode
     *
     * @return the value of Room.AcCode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getAccode() {
        return accode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.AcCode
     *
     * @param accode the value for Room.AcCode
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setAccode(String accode) {
        this.accode = accode == null ? null : accode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.RmNo
     *
     * @return the value of Room.RmNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getRmno() {
        return rmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.RmNo
     *
     * @param rmno the value for Room.RmNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setRmno(String rmno) {
        this.rmno = rmno == null ? null : rmno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Cartype
     *
     * @return the value of Room.Cartype
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Cartype
     *
     * @param cartype the value for Room.Cartype
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarNo
     *
     * @return the value of Room.CarNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getCarno() {
        return carno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarNo
     *
     * @param carno the value for Room.CarNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarno(String carno) {
        this.carno = carno == null ? null : carno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarRendateb
     *
     * @return the value of Room.CarRendateb
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getCarrendateb() {
        return carrendateb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarRendateb
     *
     * @param carrendateb the value for Room.CarRendateb
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarrendateb(Date carrendateb) {
        this.carrendateb = carrendateb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarRendatee
     *
     * @return the value of Room.CarRendatee
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getCarrendatee() {
        return carrendatee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarRendatee
     *
     * @param carrendatee the value for Room.CarRendatee
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarrendatee(Date carrendatee) {
        this.carrendatee = carrendatee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarICNo
     *
     * @return the value of Room.CarICNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getCaricno() {
        return caricno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarICNo
     *
     * @param caricno the value for Room.CarICNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCaricno(String caricno) {
        this.caricno = caricno == null ? null : caricno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.DebitNoteAddr
     *
     * @return the value of Room.DebitNoteAddr
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getDebitnoteaddr() {
        return debitnoteaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.DebitNoteAddr
     *
     * @param debitnoteaddr the value for Room.DebitNoteAddr
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDebitnoteaddr(String debitnoteaddr) {
        this.debitnoteaddr = debitnoteaddr == null ? null : debitnoteaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.BankAccntNo
     *
     * @return the value of Room.BankAccntNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getBankaccntno() {
        return bankaccntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.BankAccntNo
     *
     * @param bankaccntno the value for Room.BankAccntNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setBankaccntno(String bankaccntno) {
        this.bankaccntno = bankaccntno == null ? null : bankaccntno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CSdate
     *
     * @return the value of Room.CSdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getCsdate() {
        return csdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CSdate
     *
     * @param csdate the value for Room.CSdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCsdate(Date csdate) {
        this.csdate = csdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.idate
     *
     * @return the value of Room.idate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getIdate() {
        return idate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.idate
     *
     * @param idate the value for Room.idate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setIdate(Date idate) {
        this.idate = idate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SBDate1
     *
     * @return the value of Room.SBDate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSbdate1() {
        return sbdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SBDate1
     *
     * @param sbdate1 the value for Room.SBDate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSbdate1(Date sbdate1) {
        this.sbdate1 = sbdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SEDate1
     *
     * @return the value of Room.SEDate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSedate1() {
        return sedate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SEDate1
     *
     * @param sedate1 the value for Room.SEDate1
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSedate1(Date sedate1) {
        this.sedate1 = sedate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SBDate2
     *
     * @return the value of Room.SBDate2
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSbdate2() {
        return sbdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SBDate2
     *
     * @param sbdate2 the value for Room.SBDate2
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSbdate2(Date sbdate2) {
        this.sbdate2 = sbdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.SEDate2
     *
     * @return the value of Room.SEDate2
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getSedate2() {
        return sedate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.SEDate2
     *
     * @param sedate2 the value for Room.SEDate2
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setSedate2(Date sedate2) {
        this.sedate2 = sedate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarState
     *
     * @return the value of Room.CarState
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getCarstate() {
        return carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarState
     *
     * @param carstate the value for Room.CarState
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarstate(String carstate) {
        this.carstate = carstate == null ? null : carstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarZdateb
     *
     * @return the value of Room.CarZdateb
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getCarzdateb() {
        return carzdateb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarZdateb
     *
     * @param carzdateb the value for Room.CarZdateb
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarzdateb(Date carzdateb) {
        this.carzdateb = carzdateb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.CarZdatee
     *
     * @return the value of Room.CarZdatee
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getCarzdatee() {
        return carzdatee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.CarZdatee
     *
     * @param carzdatee the value for Room.CarZdatee
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setCarzdatee(Date carzdatee) {
        this.carzdatee = carzdatee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.PJaream
     *
     * @return the value of Room.PJaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getPjaream() {
        return pjaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.PJaream
     *
     * @param pjaream the value for Room.PJaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPjaream(BigDecimal pjaream) {
        this.pjaream = pjaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.PUaream
     *
     * @return the value of Room.PUaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getPuaream() {
        return puaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.PUaream
     *
     * @param puaream the value for Room.PUaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPuaream(BigDecimal puaream) {
        this.puaream = puaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.PGJaream
     *
     * @return the value of Room.PGJaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public BigDecimal getPgjaream() {
        return pgjaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.PGJaream
     *
     * @param pgjaream the value for Room.PGJaream
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPgjaream(BigDecimal pgjaream) {
        this.pgjaream = pgjaream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Prdate
     *
     * @return the value of Room.Prdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getPrdate() {
        return prdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Prdate
     *
     * @param prdate the value for Room.Prdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPrdate(Date prdate) {
        this.prdate = prdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.PrNo
     *
     * @return the value of Room.PrNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getPrno() {
        return prno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.PrNo
     *
     * @param prno the value for Room.PrNo
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPrno(String prno) {
        this.prno = prno == null ? null : prno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Psdate
     *
     * @return the value of Room.Psdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getPsdate() {
        return psdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Psdate
     *
     * @param psdate the value for Room.Psdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setPsdate(Date psdate) {
        this.psdate = psdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Scdate
     *
     * @return the value of Room.Scdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getScdate() {
        return scdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Scdate
     *
     * @param scdate the value for Room.Scdate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setScdate(Date scdate) {
        this.scdate = scdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.Audate
     *
     * @return the value of Room.Audate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public Date getAudate() {
        return audate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.Audate
     *
     * @param audate the value for Room.Audate
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setAudate(Date audate) {
        this.audate = audate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Room.DailyEvent
     *
     * @return the value of Room.DailyEvent
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public String getDailyevent() {
        return dailyevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Room.DailyEvent
     *
     * @param dailyevent the value for Room.DailyEvent
     *
     * @mbggenerated Tue Jan 12 15:12:04 CST 2016
     */
    public void setDailyevent(String dailyevent) {
        this.dailyevent = dailyevent == null ? null : dailyevent.trim();
    }
}