package jinsoftms.database.khdata;

import java.math.BigDecimal;
import java.util.Date;

public class YZ {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.ID
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.ICode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String icode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Name
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Nation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.JName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String jname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.BankName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.BankCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Address
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.TEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.FAX
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.IDCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String idcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.HT
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ht;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.LPerson
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String lperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.LTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ltel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.LAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String laddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String otel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.CCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Memo
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.JPerson
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String jperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.JDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private Date jdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.HaveRoom
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String haveroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.LMoney
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private BigDecimal lmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.PDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String pdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.NMoney
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private BigDecimal nmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.RoomICode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String roomicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.RoomName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.BankMc
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String bankmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.auname
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String auname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.SUnitDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private Date sunitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.SKeyCase
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String skeycase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.ORelation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String orelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OEvent
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oevent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Ooccupation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ooccupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Ohouse
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ohouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OCertificate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ocertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OClienttype
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oclienttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.ReceiptHead
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String receipthead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.IDCode2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String idcode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.IDCode3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String idcode3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OCertificate2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ocertificate2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OCertificate3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String ocertificate3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.TEL2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String tel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.TEL3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String tel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OfTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oftel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OfTEL2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oftel2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.OfTEL3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String oftel3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.FAX2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String fax2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.FAX3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String fax3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Email
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Email2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String email2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Email3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String email3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Address2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.Address3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String address3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.LEmail
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String lemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.auTel
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String autel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.auEmail
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String auemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YZ.auAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    private String auaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.ID
     *
     * @return the value of YZ.ID
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.ID
     *
     * @param id the value for YZ.ID
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.ICode
     *
     * @return the value of YZ.ICode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getIcode() {
        return icode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.ICode
     *
     * @param icode the value for YZ.ICode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setIcode(String icode) {
        this.icode = icode == null ? null : icode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Name
     *
     * @return the value of YZ.Name
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Name
     *
     * @param name the value for YZ.Name
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Nation
     *
     * @return the value of YZ.Nation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Nation
     *
     * @param nation the value for YZ.Nation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.JName
     *
     * @return the value of YZ.JName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.JName
     *
     * @param jname the value for YZ.JName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setJname(String jname) {
        this.jname = jname == null ? null : jname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.BankName
     *
     * @return the value of YZ.BankName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.BankName
     *
     * @param bankname the value for YZ.BankName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.BankCode
     *
     * @return the value of YZ.BankCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.BankCode
     *
     * @param bankcode the value for YZ.BankCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Address
     *
     * @return the value of YZ.Address
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Address
     *
     * @param address the value for YZ.Address
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.TEL
     *
     * @return the value of YZ.TEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.TEL
     *
     * @param tel the value for YZ.TEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.FAX
     *
     * @return the value of YZ.FAX
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.FAX
     *
     * @param fax the value for YZ.FAX
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.IDCode
     *
     * @return the value of YZ.IDCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getIdcode() {
        return idcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.IDCode
     *
     * @param idcode the value for YZ.IDCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setIdcode(String idcode) {
        this.idcode = idcode == null ? null : idcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.HT
     *
     * @return the value of YZ.HT
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getHt() {
        return ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.HT
     *
     * @param ht the value for YZ.HT
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setHt(String ht) {
        this.ht = ht == null ? null : ht.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.LPerson
     *
     * @return the value of YZ.LPerson
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getLperson() {
        return lperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.LPerson
     *
     * @param lperson the value for YZ.LPerson
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setLperson(String lperson) {
        this.lperson = lperson == null ? null : lperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.LTEL
     *
     * @return the value of YZ.LTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getLtel() {
        return ltel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.LTEL
     *
     * @param ltel the value for YZ.LTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setLtel(String ltel) {
        this.ltel = ltel == null ? null : ltel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.LAddress
     *
     * @return the value of YZ.LAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getLaddress() {
        return laddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.LAddress
     *
     * @param laddress the value for YZ.LAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setLaddress(String laddress) {
        this.laddress = laddress == null ? null : laddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OName
     *
     * @return the value of YZ.OName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOname() {
        return oname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OName
     *
     * @param oname the value for YZ.OName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOname(String oname) {
        this.oname = oname == null ? null : oname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OAddress
     *
     * @return the value of YZ.OAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOaddress() {
        return oaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OAddress
     *
     * @param oaddress the value for YZ.OAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOaddress(String oaddress) {
        this.oaddress = oaddress == null ? null : oaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OTEL
     *
     * @return the value of YZ.OTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOtel() {
        return otel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OTEL
     *
     * @param otel the value for YZ.OTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOtel(String otel) {
        this.otel = otel == null ? null : otel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.CCode
     *
     * @return the value of YZ.CCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getCcode() {
        return ccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.CCode
     *
     * @param ccode the value for YZ.CCode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setCcode(String ccode) {
        this.ccode = ccode == null ? null : ccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Memo
     *
     * @return the value of YZ.Memo
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Memo
     *
     * @param memo the value for YZ.Memo
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.JPerson
     *
     * @return the value of YZ.JPerson
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getJperson() {
        return jperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.JPerson
     *
     * @param jperson the value for YZ.JPerson
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setJperson(String jperson) {
        this.jperson = jperson == null ? null : jperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.JDate
     *
     * @return the value of YZ.JDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public Date getJdate() {
        return jdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.JDate
     *
     * @param jdate the value for YZ.JDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setJdate(Date jdate) {
        this.jdate = jdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.HaveRoom
     *
     * @return the value of YZ.HaveRoom
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getHaveroom() {
        return haveroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.HaveRoom
     *
     * @param haveroom the value for YZ.HaveRoom
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setHaveroom(String haveroom) {
        this.haveroom = haveroom == null ? null : haveroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.LMoney
     *
     * @return the value of YZ.LMoney
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public BigDecimal getLmoney() {
        return lmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.LMoney
     *
     * @param lmoney the value for YZ.LMoney
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setLmoney(BigDecimal lmoney) {
        this.lmoney = lmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.PDate
     *
     * @return the value of YZ.PDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.PDate
     *
     * @param pdate the value for YZ.PDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setPdate(String pdate) {
        this.pdate = pdate == null ? null : pdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.NMoney
     *
     * @return the value of YZ.NMoney
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public BigDecimal getNmoney() {
        return nmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.NMoney
     *
     * @param nmoney the value for YZ.NMoney
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setNmoney(BigDecimal nmoney) {
        this.nmoney = nmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.RoomICode
     *
     * @return the value of YZ.RoomICode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getRoomicode() {
        return roomicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.RoomICode
     *
     * @param roomicode the value for YZ.RoomICode
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setRoomicode(String roomicode) {
        this.roomicode = roomicode == null ? null : roomicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.RoomName
     *
     * @return the value of YZ.RoomName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.RoomName
     *
     * @param roomname the value for YZ.RoomName
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.BankMc
     *
     * @return the value of YZ.BankMc
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getBankmc() {
        return bankmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.BankMc
     *
     * @param bankmc the value for YZ.BankMc
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setBankmc(String bankmc) {
        this.bankmc = bankmc == null ? null : bankmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.auname
     *
     * @return the value of YZ.auname
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAuname() {
        return auname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.auname
     *
     * @param auname the value for YZ.auname
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAuname(String auname) {
        this.auname = auname == null ? null : auname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.SUnitDate
     *
     * @return the value of YZ.SUnitDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public Date getSunitdate() {
        return sunitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.SUnitDate
     *
     * @param sunitdate the value for YZ.SUnitDate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setSunitdate(Date sunitdate) {
        this.sunitdate = sunitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.SKeyCase
     *
     * @return the value of YZ.SKeyCase
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getSkeycase() {
        return skeycase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.SKeyCase
     *
     * @param skeycase the value for YZ.SKeyCase
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setSkeycase(String skeycase) {
        this.skeycase = skeycase == null ? null : skeycase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.ORelation
     *
     * @return the value of YZ.ORelation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOrelation() {
        return orelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.ORelation
     *
     * @param orelation the value for YZ.ORelation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOrelation(String orelation) {
        this.orelation = orelation == null ? null : orelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OEvent
     *
     * @return the value of YZ.OEvent
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOevent() {
        return oevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OEvent
     *
     * @param oevent the value for YZ.OEvent
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOevent(String oevent) {
        this.oevent = oevent == null ? null : oevent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Ooccupation
     *
     * @return the value of YZ.Ooccupation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOoccupation() {
        return ooccupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Ooccupation
     *
     * @param ooccupation the value for YZ.Ooccupation
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOoccupation(String ooccupation) {
        this.ooccupation = ooccupation == null ? null : ooccupation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Ohouse
     *
     * @return the value of YZ.Ohouse
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOhouse() {
        return ohouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Ohouse
     *
     * @param ohouse the value for YZ.Ohouse
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOhouse(String ohouse) {
        this.ohouse = ohouse == null ? null : ohouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OCertificate
     *
     * @return the value of YZ.OCertificate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOcertificate() {
        return ocertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OCertificate
     *
     * @param ocertificate the value for YZ.OCertificate
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOcertificate(String ocertificate) {
        this.ocertificate = ocertificate == null ? null : ocertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OClienttype
     *
     * @return the value of YZ.OClienttype
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOclienttype() {
        return oclienttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OClienttype
     *
     * @param oclienttype the value for YZ.OClienttype
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOclienttype(String oclienttype) {
        this.oclienttype = oclienttype == null ? null : oclienttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.ReceiptHead
     *
     * @return the value of YZ.ReceiptHead
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getReceipthead() {
        return receipthead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.ReceiptHead
     *
     * @param receipthead the value for YZ.ReceiptHead
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setReceipthead(String receipthead) {
        this.receipthead = receipthead == null ? null : receipthead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.IDCode2
     *
     * @return the value of YZ.IDCode2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getIdcode2() {
        return idcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.IDCode2
     *
     * @param idcode2 the value for YZ.IDCode2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setIdcode2(String idcode2) {
        this.idcode2 = idcode2 == null ? null : idcode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.IDCode3
     *
     * @return the value of YZ.IDCode3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getIdcode3() {
        return idcode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.IDCode3
     *
     * @param idcode3 the value for YZ.IDCode3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setIdcode3(String idcode3) {
        this.idcode3 = idcode3 == null ? null : idcode3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OCertificate2
     *
     * @return the value of YZ.OCertificate2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOcertificate2() {
        return ocertificate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OCertificate2
     *
     * @param ocertificate2 the value for YZ.OCertificate2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOcertificate2(String ocertificate2) {
        this.ocertificate2 = ocertificate2 == null ? null : ocertificate2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OCertificate3
     *
     * @return the value of YZ.OCertificate3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOcertificate3() {
        return ocertificate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OCertificate3
     *
     * @param ocertificate3 the value for YZ.OCertificate3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOcertificate3(String ocertificate3) {
        this.ocertificate3 = ocertificate3 == null ? null : ocertificate3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.TEL2
     *
     * @return the value of YZ.TEL2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getTel2() {
        return tel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.TEL2
     *
     * @param tel2 the value for YZ.TEL2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setTel2(String tel2) {
        this.tel2 = tel2 == null ? null : tel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.TEL3
     *
     * @return the value of YZ.TEL3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getTel3() {
        return tel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.TEL3
     *
     * @param tel3 the value for YZ.TEL3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setTel3(String tel3) {
        this.tel3 = tel3 == null ? null : tel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OfTEL
     *
     * @return the value of YZ.OfTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOftel() {
        return oftel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OfTEL
     *
     * @param oftel the value for YZ.OfTEL
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOftel(String oftel) {
        this.oftel = oftel == null ? null : oftel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OfTEL2
     *
     * @return the value of YZ.OfTEL2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOftel2() {
        return oftel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OfTEL2
     *
     * @param oftel2 the value for YZ.OfTEL2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOftel2(String oftel2) {
        this.oftel2 = oftel2 == null ? null : oftel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.OfTEL3
     *
     * @return the value of YZ.OfTEL3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getOftel3() {
        return oftel3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.OfTEL3
     *
     * @param oftel3 the value for YZ.OfTEL3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setOftel3(String oftel3) {
        this.oftel3 = oftel3 == null ? null : oftel3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.FAX2
     *
     * @return the value of YZ.FAX2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getFax2() {
        return fax2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.FAX2
     *
     * @param fax2 the value for YZ.FAX2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setFax2(String fax2) {
        this.fax2 = fax2 == null ? null : fax2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.FAX3
     *
     * @return the value of YZ.FAX3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getFax3() {
        return fax3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.FAX3
     *
     * @param fax3 the value for YZ.FAX3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setFax3(String fax3) {
        this.fax3 = fax3 == null ? null : fax3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Email
     *
     * @return the value of YZ.Email
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Email
     *
     * @param email the value for YZ.Email
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Email2
     *
     * @return the value of YZ.Email2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Email2
     *
     * @param email2 the value for YZ.Email2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setEmail2(String email2) {
        this.email2 = email2 == null ? null : email2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Email3
     *
     * @return the value of YZ.Email3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getEmail3() {
        return email3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Email3
     *
     * @param email3 the value for YZ.Email3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setEmail3(String email3) {
        this.email3 = email3 == null ? null : email3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Address2
     *
     * @return the value of YZ.Address2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Address2
     *
     * @param address2 the value for YZ.Address2
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.Address3
     *
     * @return the value of YZ.Address3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.Address3
     *
     * @param address3 the value for YZ.Address3
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAddress3(String address3) {
        this.address3 = address3 == null ? null : address3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.LEmail
     *
     * @return the value of YZ.LEmail
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getLemail() {
        return lemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.LEmail
     *
     * @param lemail the value for YZ.LEmail
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setLemail(String lemail) {
        this.lemail = lemail == null ? null : lemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.auTel
     *
     * @return the value of YZ.auTel
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAutel() {
        return autel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.auTel
     *
     * @param autel the value for YZ.auTel
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAutel(String autel) {
        this.autel = autel == null ? null : autel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.auEmail
     *
     * @return the value of YZ.auEmail
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAuemail() {
        return auemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.auEmail
     *
     * @param auemail the value for YZ.auEmail
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAuemail(String auemail) {
        this.auemail = auemail == null ? null : auemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YZ.auAddress
     *
     * @return the value of YZ.auAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public String getAuaddress() {
        return auaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YZ.auAddress
     *
     * @param auaddress the value for YZ.auAddress
     *
     * @mbggenerated Tue Dec 29 14:53:26 CST 2015
     */
    public void setAuaddress(String auaddress) {
        this.auaddress = auaddress == null ? null : auaddress.trim();
    }
}