package jinsoftms.database.khdata;

import java.math.BigDecimal;
import java.util.Date;

public class ZH {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.ID
     *
     * @mbggenerated Tue Dec 29 14:53:01 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.ICode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String icode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Name
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Nation
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.JName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String jname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Person
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Address
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.TAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String taddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.TEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.FAX
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Type
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.BDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date bdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.EDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date edate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Kind
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.LPerson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String lperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.LTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String ltel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.OName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String oname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.OAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String oaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.OTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String otel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.GCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String gcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Memo
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.JPerson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String jperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.JDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date jdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.HaveRoom
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String haveroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.LMoney
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private BigDecimal lmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.PDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String pdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.NMoney
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private BigDecimal nmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.RoomICode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String roomicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.RoomName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.BankName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.BankCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Workname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String workname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.WorkDetial
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String workdetial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Rent
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private BigDecimal rent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.SKeyCase
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String skeycase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.SUnitDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date sunitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.ManageSdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date managesdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.ReceiptHead
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String receipthead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.ckdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date ckdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.BankMc
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String bankmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.IDCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String idcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.IDType
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String idtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Gplace
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String gplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Gperson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String gperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Gtel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String gtel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.OfTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String oftel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.Email
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.waName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String waname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.waTel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String watel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.waEmail
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String waemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.waAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String waaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.auName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String auname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.auTel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String autel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.auEmail
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String auemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.auAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String auaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.incheck
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String incheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.goonmemo
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String goonmemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.firstpassname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String firstpassname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.firstpasstel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String firstpasstel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.secondpassname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String secondpassname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.secondpasstel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String secondpasstel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.plcdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private Date plcdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.plcname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String plcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.plctel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String plctel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZH.plcrmno
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    private String plcrmno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.ID
     *
     * @return the value of ZH.ID
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.ID
     *
     * @param id the value for ZH.ID
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.ICode
     *
     * @return the value of ZH.ICode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getIcode() {
        return icode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.ICode
     *
     * @param icode the value for ZH.ICode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setIcode(String icode) {
        this.icode = icode == null ? null : icode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Name
     *
     * @return the value of ZH.Name
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Name
     *
     * @param name the value for ZH.Name
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Nation
     *
     * @return the value of ZH.Nation
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Nation
     *
     * @param nation the value for ZH.Nation
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.JName
     *
     * @return the value of ZH.JName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.JName
     *
     * @param jname the value for ZH.JName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setJname(String jname) {
        this.jname = jname == null ? null : jname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Person
     *
     * @return the value of ZH.Person
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Person
     *
     * @param person the value for ZH.Person
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Address
     *
     * @return the value of ZH.Address
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Address
     *
     * @param address the value for ZH.Address
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.TAddress
     *
     * @return the value of ZH.TAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getTaddress() {
        return taddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.TAddress
     *
     * @param taddress the value for ZH.TAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setTaddress(String taddress) {
        this.taddress = taddress == null ? null : taddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.TEL
     *
     * @return the value of ZH.TEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.TEL
     *
     * @param tel the value for ZH.TEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.FAX
     *
     * @return the value of ZH.FAX
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.FAX
     *
     * @param fax the value for ZH.FAX
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Type
     *
     * @return the value of ZH.Type
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Type
     *
     * @param type the value for ZH.Type
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.BDate
     *
     * @return the value of ZH.BDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getBdate() {
        return bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.BDate
     *
     * @param bdate the value for ZH.BDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setBdate(Date bdate) {
        this.bdate = bdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.EDate
     *
     * @return the value of ZH.EDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.EDate
     *
     * @param edate the value for ZH.EDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setEdate(Date edate) {
        this.edate = edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Kind
     *
     * @return the value of ZH.Kind
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Kind
     *
     * @param kind the value for ZH.Kind
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.LPerson
     *
     * @return the value of ZH.LPerson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getLperson() {
        return lperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.LPerson
     *
     * @param lperson the value for ZH.LPerson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setLperson(String lperson) {
        this.lperson = lperson == null ? null : lperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.LTEL
     *
     * @return the value of ZH.LTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getLtel() {
        return ltel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.LTEL
     *
     * @param ltel the value for ZH.LTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setLtel(String ltel) {
        this.ltel = ltel == null ? null : ltel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.OName
     *
     * @return the value of ZH.OName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getOname() {
        return oname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.OName
     *
     * @param oname the value for ZH.OName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setOname(String oname) {
        this.oname = oname == null ? null : oname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.OAddress
     *
     * @return the value of ZH.OAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getOaddress() {
        return oaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.OAddress
     *
     * @param oaddress the value for ZH.OAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setOaddress(String oaddress) {
        this.oaddress = oaddress == null ? null : oaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.OTEL
     *
     * @return the value of ZH.OTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getOtel() {
        return otel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.OTEL
     *
     * @param otel the value for ZH.OTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setOtel(String otel) {
        this.otel = otel == null ? null : otel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.GCode
     *
     * @return the value of ZH.GCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getGcode() {
        return gcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.GCode
     *
     * @param gcode the value for ZH.GCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setGcode(String gcode) {
        this.gcode = gcode == null ? null : gcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Memo
     *
     * @return the value of ZH.Memo
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Memo
     *
     * @param memo the value for ZH.Memo
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.JPerson
     *
     * @return the value of ZH.JPerson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getJperson() {
        return jperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.JPerson
     *
     * @param jperson the value for ZH.JPerson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setJperson(String jperson) {
        this.jperson = jperson == null ? null : jperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.JDate
     *
     * @return the value of ZH.JDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getJdate() {
        return jdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.JDate
     *
     * @param jdate the value for ZH.JDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setJdate(Date jdate) {
        this.jdate = jdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.HaveRoom
     *
     * @return the value of ZH.HaveRoom
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getHaveroom() {
        return haveroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.HaveRoom
     *
     * @param haveroom the value for ZH.HaveRoom
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setHaveroom(String haveroom) {
        this.haveroom = haveroom == null ? null : haveroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.LMoney
     *
     * @return the value of ZH.LMoney
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public BigDecimal getLmoney() {
        return lmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.LMoney
     *
     * @param lmoney the value for ZH.LMoney
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setLmoney(BigDecimal lmoney) {
        this.lmoney = lmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.PDate
     *
     * @return the value of ZH.PDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.PDate
     *
     * @param pdate the value for ZH.PDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setPdate(String pdate) {
        this.pdate = pdate == null ? null : pdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.NMoney
     *
     * @return the value of ZH.NMoney
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public BigDecimal getNmoney() {
        return nmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.NMoney
     *
     * @param nmoney the value for ZH.NMoney
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setNmoney(BigDecimal nmoney) {
        this.nmoney = nmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.RoomICode
     *
     * @return the value of ZH.RoomICode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getRoomicode() {
        return roomicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.RoomICode
     *
     * @param roomicode the value for ZH.RoomICode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setRoomicode(String roomicode) {
        this.roomicode = roomicode == null ? null : roomicode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.RoomName
     *
     * @return the value of ZH.RoomName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.RoomName
     *
     * @param roomname the value for ZH.RoomName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.BankName
     *
     * @return the value of ZH.BankName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.BankName
     *
     * @param bankname the value for ZH.BankName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.BankCode
     *
     * @return the value of ZH.BankCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.BankCode
     *
     * @param bankcode the value for ZH.BankCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Workname
     *
     * @return the value of ZH.Workname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getWorkname() {
        return workname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Workname
     *
     * @param workname the value for ZH.Workname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setWorkname(String workname) {
        this.workname = workname == null ? null : workname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.WorkDetial
     *
     * @return the value of ZH.WorkDetial
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getWorkdetial() {
        return workdetial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.WorkDetial
     *
     * @param workdetial the value for ZH.WorkDetial
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setWorkdetial(String workdetial) {
        this.workdetial = workdetial == null ? null : workdetial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Rent
     *
     * @return the value of ZH.Rent
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public BigDecimal getRent() {
        return rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Rent
     *
     * @param rent the value for ZH.Rent
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setRent(BigDecimal rent) {
        this.rent = rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.SKeyCase
     *
     * @return the value of ZH.SKeyCase
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getSkeycase() {
        return skeycase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.SKeyCase
     *
     * @param skeycase the value for ZH.SKeyCase
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setSkeycase(String skeycase) {
        this.skeycase = skeycase == null ? null : skeycase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.SUnitDate
     *
     * @return the value of ZH.SUnitDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getSunitdate() {
        return sunitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.SUnitDate
     *
     * @param sunitdate the value for ZH.SUnitDate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setSunitdate(Date sunitdate) {
        this.sunitdate = sunitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.ManageSdate
     *
     * @return the value of ZH.ManageSdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getManagesdate() {
        return managesdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.ManageSdate
     *
     * @param managesdate the value for ZH.ManageSdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setManagesdate(Date managesdate) {
        this.managesdate = managesdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.ReceiptHead
     *
     * @return the value of ZH.ReceiptHead
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getReceipthead() {
        return receipthead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.ReceiptHead
     *
     * @param receipthead the value for ZH.ReceiptHead
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setReceipthead(String receipthead) {
        this.receipthead = receipthead == null ? null : receipthead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.ckdate
     *
     * @return the value of ZH.ckdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getCkdate() {
        return ckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.ckdate
     *
     * @param ckdate the value for ZH.ckdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setCkdate(Date ckdate) {
        this.ckdate = ckdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.BankMc
     *
     * @return the value of ZH.BankMc
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getBankmc() {
        return bankmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.BankMc
     *
     * @param bankmc the value for ZH.BankMc
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setBankmc(String bankmc) {
        this.bankmc = bankmc == null ? null : bankmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.IDCode
     *
     * @return the value of ZH.IDCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getIdcode() {
        return idcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.IDCode
     *
     * @param idcode the value for ZH.IDCode
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setIdcode(String idcode) {
        this.idcode = idcode == null ? null : idcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.IDType
     *
     * @return the value of ZH.IDType
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.IDType
     *
     * @param idtype the value for ZH.IDType
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype == null ? null : idtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Gplace
     *
     * @return the value of ZH.Gplace
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getGplace() {
        return gplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Gplace
     *
     * @param gplace the value for ZH.Gplace
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setGplace(String gplace) {
        this.gplace = gplace == null ? null : gplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Gperson
     *
     * @return the value of ZH.Gperson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getGperson() {
        return gperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Gperson
     *
     * @param gperson the value for ZH.Gperson
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setGperson(String gperson) {
        this.gperson = gperson == null ? null : gperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Gtel
     *
     * @return the value of ZH.Gtel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getGtel() {
        return gtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Gtel
     *
     * @param gtel the value for ZH.Gtel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setGtel(String gtel) {
        this.gtel = gtel == null ? null : gtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.OfTEL
     *
     * @return the value of ZH.OfTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getOftel() {
        return oftel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.OfTEL
     *
     * @param oftel the value for ZH.OfTEL
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setOftel(String oftel) {
        this.oftel = oftel == null ? null : oftel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.Email
     *
     * @return the value of ZH.Email
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.Email
     *
     * @param email the value for ZH.Email
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.waName
     *
     * @return the value of ZH.waName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getWaname() {
        return waname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.waName
     *
     * @param waname the value for ZH.waName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setWaname(String waname) {
        this.waname = waname == null ? null : waname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.waTel
     *
     * @return the value of ZH.waTel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getWatel() {
        return watel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.waTel
     *
     * @param watel the value for ZH.waTel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setWatel(String watel) {
        this.watel = watel == null ? null : watel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.waEmail
     *
     * @return the value of ZH.waEmail
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getWaemail() {
        return waemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.waEmail
     *
     * @param waemail the value for ZH.waEmail
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setWaemail(String waemail) {
        this.waemail = waemail == null ? null : waemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.waAddress
     *
     * @return the value of ZH.waAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getWaaddress() {
        return waaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.waAddress
     *
     * @param waaddress the value for ZH.waAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setWaaddress(String waaddress) {
        this.waaddress = waaddress == null ? null : waaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.auName
     *
     * @return the value of ZH.auName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getAuname() {
        return auname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.auName
     *
     * @param auname the value for ZH.auName
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setAuname(String auname) {
        this.auname = auname == null ? null : auname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.auTel
     *
     * @return the value of ZH.auTel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getAutel() {
        return autel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.auTel
     *
     * @param autel the value for ZH.auTel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setAutel(String autel) {
        this.autel = autel == null ? null : autel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.auEmail
     *
     * @return the value of ZH.auEmail
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getAuemail() {
        return auemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.auEmail
     *
     * @param auemail the value for ZH.auEmail
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setAuemail(String auemail) {
        this.auemail = auemail == null ? null : auemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.auAddress
     *
     * @return the value of ZH.auAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getAuaddress() {
        return auaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.auAddress
     *
     * @param auaddress the value for ZH.auAddress
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setAuaddress(String auaddress) {
        this.auaddress = auaddress == null ? null : auaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.incheck
     *
     * @return the value of ZH.incheck
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getIncheck() {
        return incheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.incheck
     *
     * @param incheck the value for ZH.incheck
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setIncheck(String incheck) {
        this.incheck = incheck == null ? null : incheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.goonmemo
     *
     * @return the value of ZH.goonmemo
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getGoonmemo() {
        return goonmemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.goonmemo
     *
     * @param goonmemo the value for ZH.goonmemo
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setGoonmemo(String goonmemo) {
        this.goonmemo = goonmemo == null ? null : goonmemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.firstpassname
     *
     * @return the value of ZH.firstpassname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getFirstpassname() {
        return firstpassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.firstpassname
     *
     * @param firstpassname the value for ZH.firstpassname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setFirstpassname(String firstpassname) {
        this.firstpassname = firstpassname == null ? null : firstpassname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.firstpasstel
     *
     * @return the value of ZH.firstpasstel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getFirstpasstel() {
        return firstpasstel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.firstpasstel
     *
     * @param firstpasstel the value for ZH.firstpasstel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setFirstpasstel(String firstpasstel) {
        this.firstpasstel = firstpasstel == null ? null : firstpasstel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.secondpassname
     *
     * @return the value of ZH.secondpassname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getSecondpassname() {
        return secondpassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.secondpassname
     *
     * @param secondpassname the value for ZH.secondpassname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setSecondpassname(String secondpassname) {
        this.secondpassname = secondpassname == null ? null : secondpassname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.secondpasstel
     *
     * @return the value of ZH.secondpasstel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getSecondpasstel() {
        return secondpasstel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.secondpasstel
     *
     * @param secondpasstel the value for ZH.secondpasstel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setSecondpasstel(String secondpasstel) {
        this.secondpasstel = secondpasstel == null ? null : secondpasstel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.plcdate
     *
     * @return the value of ZH.plcdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public Date getPlcdate() {
        return plcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.plcdate
     *
     * @param plcdate the value for ZH.plcdate
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setPlcdate(Date plcdate) {
        this.plcdate = plcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.plcname
     *
     * @return the value of ZH.plcname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getPlcname() {
        return plcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.plcname
     *
     * @param plcname the value for ZH.plcname
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setPlcname(String plcname) {
        this.plcname = plcname == null ? null : plcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.plctel
     *
     * @return the value of ZH.plctel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getPlctel() {
        return plctel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.plctel
     *
     * @param plctel the value for ZH.plctel
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setPlctel(String plctel) {
        this.plctel = plctel == null ? null : plctel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZH.plcrmno
     *
     * @return the value of ZH.plcrmno
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public String getPlcrmno() {
        return plcrmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZH.plcrmno
     *
     * @param plcrmno the value for ZH.plcrmno
     *
     * @mbggenerated Tue Dec 29 14:53:02 CST 2015
     */
    public void setPlcrmno(String plcrmno) {
        this.plcrmno = plcrmno == null ? null : plcrmno.trim();
    }
}